---
linux: #Группа хостов 
  children: #Обозначение, что будет подгруппа хостов
    nginx: #Имя подгруппы хостов
      hosts: #Узлы группы
        vm_1: #Имя машины
          ansible_host: 158.160.112.243 #Адрес машины
          ansible_user: ubuntu
          ansible_python_interpreter: /usr/bin/python3
    web:
      hosts:
        vm_2: #Имя машины
          ansible_host: 158.160.99.225 #Адрес машины
          ansible_user: ubuntu
          ansible_python_interpreter: /usr/bin/python3
        vm_3: #Имя машины
          ansible_host: 51.250.84.177 #Адрес машины
          ansible_user: debian
          ansible_python_interpreter: /usr/bin/python3
  vars: #Переменные, доступные или используемые для всех подгрупп
    ansible_connection: ssh #тип подключения
    ansible_become: true #Становиться ли другим пользователем после подключения
