---
- name: Установка стандартных пакетов
  hosts: all
  become: true
  roles:
    - role: default_packages
  tags:
    - install_packages

- name: Установка и настройка проксирующего Nginx
  hosts: nginx # Будет работать на узлах в группе nginx
  roles:
    - role: nginx_proxy
  tags:
    - nginx_proxy

- name: Установка и настройка nginx c кастомной страницей
  hosts: web # Будет работать на узлах в группе nginx
  roles:
    - role: nginx_web
  tags:
    - nginx_web
